#############################################################################
# Makefile for building: moonlight-qt
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  moonlight-qt.pro
# Template: subdirs
# Command: /usr/lib/qt5/bin/qmake -o Makefile moonlight-qt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = moonlight-qt1.0.0
DISTDIR = /home/rasulbek/muslim-projects/moonlight-qt/.tmp/moonlight-qt1.0.0
SUBTARGETS    =  \
		sub-moonlight-common-c \
		sub-qmdnsengine \
		sub-app \
		sub-h264bitstream


sub-moonlight-common-c-qmake_all:  FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro
	cd moonlight-common-c/ && $(MAKE) -f Makefile qmake_all
sub-moonlight-common-c: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile
sub-moonlight-common-c-make_first: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile 
sub-moonlight-common-c-all: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile all
sub-moonlight-common-c-clean: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile clean
sub-moonlight-common-c-distclean: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile distclean
sub-moonlight-common-c-install_subtargets: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile install
sub-moonlight-common-c-uninstall_subtargets: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile uninstall
sub-qmdnsengine-qmake_all:  FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro
	cd qmdnsengine/ && $(MAKE) -f Makefile qmake_all
sub-qmdnsengine: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile
sub-qmdnsengine-make_first: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile 
sub-qmdnsengine-all: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile all
sub-qmdnsengine-clean: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile clean
sub-qmdnsengine-distclean: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile distclean
sub-qmdnsengine-install_subtargets: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile install
sub-qmdnsengine-uninstall_subtargets: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-qmdnsengine-qmake_all sub-moonlight-common-c-qmake_all sub-h264bitstream-qmake_all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro
	cd app/ && $(MAKE) -f Makefile qmake_all
sub-app: sub-qmdnsengine \
		sub-moonlight-common-c \
		sub-h264bitstream FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile
sub-app-make_first: sub-qmdnsengine-make_first sub-moonlight-common-c-make_first sub-h264bitstream-make_first FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile 
sub-app-all: sub-qmdnsengine-all sub-moonlight-common-c-all sub-h264bitstream-all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile all
sub-app-clean: sub-qmdnsengine-clean sub-moonlight-common-c-clean sub-h264bitstream-clean FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile clean
sub-app-distclean: sub-qmdnsengine-distclean sub-moonlight-common-c-distclean sub-h264bitstream-distclean FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets: sub-qmdnsengine-install_subtargets sub-moonlight-common-c-install_subtargets sub-h264bitstream-install_subtargets FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets: sub-qmdnsengine-uninstall_subtargets sub-moonlight-common-c-uninstall_subtargets sub-h264bitstream-uninstall_subtargets FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile uninstall
sub-h264bitstream-qmake_all:  FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro
	cd h264bitstream/ && $(MAKE) -f Makefile qmake_all
sub-h264bitstream: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile
sub-h264bitstream-make_first: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile 
sub-h264bitstream-all: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile all
sub-h264bitstream-clean: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile clean
sub-h264bitstream-distclean: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile distclean
sub-h264bitstream-install_subtargets: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile install
sub-h264bitstream-uninstall_subtargets: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile uninstall

Makefile: moonlight-qt.pro .qmake.cache /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.cache \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/configure_base.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/configure.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		moonlight-qt.pro
	$(QMAKE) -o Makefile moonlight-qt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.cache:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/configure_base.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/configure.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
moonlight-qt.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile moonlight-qt.pro

qmake_all: sub-moonlight-common-c-qmake_all sub-qmdnsengine-qmake_all sub-app-qmake_all sub-h264bitstream-qmake_all FORCE

make_first: sub-moonlight-common-c-make_first sub-qmdnsengine-make_first sub-app-make_first sub-h264bitstream-make_first  FORCE
all: sub-moonlight-common-c-all sub-qmdnsengine-all sub-app-all sub-h264bitstream-all  FORCE
clean: sub-moonlight-common-c-clean sub-qmdnsengine-clean sub-app-clean sub-h264bitstream-clean  FORCE
distclean: sub-moonlight-common-c-distclean sub-qmdnsengine-distclean sub-app-distclean sub-h264bitstream-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-moonlight-common-c-install_subtargets sub-qmdnsengine-install_subtargets sub-app-install_subtargets sub-h264bitstream-install_subtargets FORCE
uninstall_subtargets: sub-moonlight-common-c-uninstall_subtargets sub-qmdnsengine-uninstall_subtargets sub-app-uninstall_subtargets sub-h264bitstream-uninstall_subtargets FORCE

sub-moonlight-common-c-debug:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile debug
sub-qmdnsengine-debug:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile debug
sub-app-debug: sub-qmdnsengine-debug sub-moonlight-common-c-debug sub-h264bitstream-debug
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile debug
sub-h264bitstream-debug:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile debug
debug: sub-moonlight-common-c-debug sub-qmdnsengine-debug sub-app-debug sub-h264bitstream-debug

sub-moonlight-common-c-release:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile release
sub-qmdnsengine-release:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile release
sub-app-release: sub-qmdnsengine-release sub-moonlight-common-c-release sub-h264bitstream-release
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile release
sub-h264bitstream-release:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile release
release: sub-moonlight-common-c-release sub-qmdnsengine-release sub-app-release sub-h264bitstream-release

sub-moonlight-common-c-check:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile check
sub-qmdnsengine-check:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile check
sub-app-check: sub-qmdnsengine-check sub-moonlight-common-c-check sub-h264bitstream-check
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile check
sub-h264bitstream-check:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile check
check: sub-moonlight-common-c-check sub-qmdnsengine-check sub-app-check sub-h264bitstream-check

sub-moonlight-common-c-benchmark:
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -f Makefile benchmark
sub-qmdnsengine-benchmark:
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -f Makefile benchmark
sub-app-benchmark: sub-qmdnsengine-benchmark sub-moonlight-common-c-benchmark sub-h264bitstream-benchmark
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -f Makefile benchmark
sub-h264bitstream-benchmark:
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-moonlight-common-c-benchmark sub-qmdnsengine-benchmark sub-app-benchmark sub-h264bitstream-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-moonlight-common-c-distdir sub-qmdnsengine-distdir sub-app-distdir sub-h264bitstream-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.stash moonlight-qt.pro $(DISTDIR)/

sub-moonlight-common-c-distdir: FORCE
	@test -d moonlight-common-c/ || mkdir -p moonlight-common-c/
	cd moonlight-common-c/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/moonlight-common-c/moonlight-common-c.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/moonlight-common-c

sub-qmdnsengine-distdir: FORCE
	@test -d qmdnsengine/ || mkdir -p qmdnsengine/
	cd qmdnsengine/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/qmdnsengine/qmdnsengine.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/qmdnsengine

sub-app-distdir: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/app/app.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/app

sub-h264bitstream-distdir: FORCE
	@test -d h264bitstream/ || mkdir -p h264bitstream/
	cd h264bitstream/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/rasulbek/muslim-projects/moonlight-qt/h264bitstream/h264bitstream.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/h264bitstream

